Config = {}
Config.Locale = GetConvar('esx:locale', 'en')
Config.BillingDistance = 10.0
Config.BillingCooldown = 3000
Config.MinimumBillingGrade = 1
Config.MaxBillAmount = 100000
Config.MaxDailyBillAmount = 250000
Config.MaxBillLabelLength = 80
Config.HighBillConfirmationAmount = 50000
Config.HighBillConfirmationTimeout = 30000
Config.BillingMinimumGrades = {}
